-- PostgreSQL schema generated from Java JPA models

CREATE TABLE genre (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL
);

CREATE TABLE author (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name varchar(255) NOT NULL
);

CREATE TABLE app_user (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username varchar(50) NOT NULL,
  profile_pic varchar(512),
  email varchar(255) NOT NULL,
  password_hash varchar(255) NOT NULL,
  is_verified boolean NOT NULL DEFAULT false,
  verification_code varchar(6) NOT NULL
);

CREATE TABLE book (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title varchar(255) NOT NULL,
  description text NOT NULL,
  release_year smallint NOT NULL,
  book_cover varchar(512) NOT NULL,
  pdf varchar(512) NOT NULL,
  slug varchar(255) NOT NULL,
  author_id integer,
  genre_id integer,
  CONSTRAINT fk_book_author FOREIGN KEY (author_id) REFERENCES author(id) ON DELETE SET NULL,
  CONSTRAINT fk_book_genre FOREIGN KEY (genre_id) REFERENCES genre(id) ON DELETE SET NULL
);

CREATE TABLE favorite_book (
  user_id integer NOT NULL,
  book_id integer NOT NULL,
  PRIMARY KEY (user_id, book_id),
  CONSTRAINT fk_fav_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
  CONSTRAINT fk_fav_book FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE
);

CREATE TABLE reading_list_book (
  user_id integer NOT NULL,
  book_id integer NOT NULL,
  current_page integer NOT NULL DEFAULT 0,
  is_complete boolean NOT NULL DEFAULT false,
  PRIMARY KEY (user_id, book_id),
  CONSTRAINT fk_rl_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
  CONSTRAINT fk_rl_book FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE
);

CREATE TABLE review (
  user_id integer NOT NULL,
  book_id integer NOT NULL,
  rate integer NOT NULL CHECK (rate BETWEEN 1 AND 5),
  comment varchar(15) NOT NULL,
  PRIMARY KEY (user_id, book_id),
  CONSTRAINT fk_review_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
  CONSTRAINT fk_review_book FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE
);

CREATE TABLE quiz_question (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  book_id integer,
  question_text text NOT NULL,
  option_a varchar(255) NOT NULL,
  option_b varchar(255) NOT NULL,
  option_c varchar(255) NOT NULL,
  option_d varchar(255) NOT NULL,
  correct_answer char(1) NOT NULL,
  CONSTRAINT fk_qq_book FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE SET NULL
);

CREATE TABLE quiz_result (
  user_id integer NOT NULL,
  book_id integer NOT NULL,
  correct_answers integer NOT NULL CHECK (correct_answers >= 0 AND correct_answers <= 10),
  points integer NOT NULL CHECK (points >= 0 AND points <= 100),
  randon_answers_choosed integer NOT NULL CHECK (randon_answers_choosed >= 0),
  PRIMARY KEY (user_id, book_id),
  CONSTRAINT fk_qr_user FOREIGN KEY (user_id) REFERENCES app_user(id) ON DELETE CASCADE,
  CONSTRAINT fk_qr_book FOREIGN KEY (book_id) REFERENCES book(id) ON DELETE CASCADE
);

-- Optional: basic indexes
CREATE INDEX idx_book_slug ON book(slug);
CREATE INDEX idx_app_user_email ON app_user(email);
